owner: "cxe-development-team"
repo: "status-page"

sites:
  - name: "Dashboard ( Soon )"
    url: https://www.youtube.com/
  - name: "Free - Panel ( Soon )"
    url: https://status.cxe.my.id/
  - name: "Free - Node SG 2 ( Soon )"
    check: "tcp-ping"
    url: free-sg2.cxe.my.id
    port: 8080
  - name: "Paid (new) - Node SG 2"
    check: "tcp-ping"
    url: paid-sg2.cxe.my.id
    port: 8080
  - name: "Paid - Panel"
    url: https://panelcxe.hexagonn.my.id/
  - name: "Paid - Node SG 1"
    check: "tcp-ping"
    url: sgp1.hexagonn.my.id
    port: 8080
  - name: "Paid - Node SG 2"
    check: "tcp-ping"
    url: sgp2.hexagonn.my.id
    port: 8080

status-website:
  cname: status.cxe.my.id
  logoUrl: https://cdn.discordapp.com/icons/1106459111274594324/a_de6709655f7d2091cca473d62a7ddcba.gif
  favicon: https://cdn.discordapp.com/icons/1106459111274594324/a_de6709655f7d2091cca473d62a7ddcba.gif
  name: Cxe
  introTitle: "**Cxe** for monitoring."
  introMessage: "Welcome to Cxe Status!"
  theme: night
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Free - Panel ( Soon )
      href: https://portal.cxe.my.id/
    - title: Paid - Panel ( Soon )
      href: https://paidcxe.hexagonn.my.id/

i18n:
  footer: "Made with 💖 by [Hexagonn](https://www.hexagonn.my.id/)"
